version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: otp-db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      mongo:
        condition: service_started

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      MAILDEV_HOST: maildev
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
    ports:
      - "8082:1080"

  multi-factor-authentication:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      SPRING_DATASOURCE_URL: mongodb://root:password@mongo:27017/
      SPRING_DATASOURCE_DATABASE: otp-db
      MAILDEV_HOST: maildev
      MAILDEV_SMTP_PORT: 1025
    depends_on:
      mongo:
        condition: service_started
      maildev:
        condition: service_started