spring:
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL:mongodb://root:password@localhost:27017/}
      database: ${MONGO_INITDB_DATABASE:otp-db}
  mail:
    host: ${MAILDEV_HOST:localhost}
    port: ${MAILDEV_SMTP_PORT:1025}